version: '3.8'

services:
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./utils/docker/Dockerfile.frontend
    env_file:
      - .env
    ports:
      - 80:8080

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./utils/docker/Dockerfile.backend
    env_file:
      - .env
    volumes:
      - static_volume:/app/backend/server/django_static
      - swiftview_data:/usr/src/app/shared
    depends_on:
      - database

  database:
    restart: unless-stopped
    image: keinos/sqlite3:latest
    stdin_open: true
    tty: true
    expose:
      - '5432:5432'
    volumes:
      - swiftview_data:/data

volumes:
  swiftview_data:
    driver: local
  static_volume: {}
